var tweaks = [
  {
    "description": "Set custom header text",
    "action": "setInnerText",
    "selector": "h2:first-of-type",
    "value": "This is a tweaked header",
  },
  {
    "description": "Set custom inner HTML",
    "action": "setInnerHtml",
    "selector": ".inner-html",
    "value": "<strong>strong <i>i</i></strong>",
  },
  {
    "description": "Add class name",
    "action": "addClass",
    "selector": "#red",
    "value": "red-border",
  },
  {
    "description": "Remove class name",
    "action": "removeClass",
    "selector": "#red2",
    "value": "green-border",
  },
  {
    "description": "Remove element",
    "action": "remove",
    "selector": "#to_remove",
  },
  {
    "description": "Add style tag",
    "action": "addStyle",
    "value": ".add-style>div \{ background: red; \}",
  },
  {
    "description": "Add script tag: head + innerHTML",
    "action": "addScript",
    "location": "head",
    "src": "",
    "value": "console.log('addScript: Add script tag: head + innerHTML')",
  },
  {
    "description": "Add script tag: body + src",
    "action": "addScript",
    "location": "body",
    "src": "demo/sample.js",
  },
  {
    "description": "Execute script: call namespaced function",
    "action": "execute",
    "value": "hardCoded.testFunc",
  },
  {
    "description": "Execute script with eval",
    "action": "execute",
    "value": "console.log('execute: eval is bad')",
  },
  {
    "description": "Set avatar to batman",
    "action": "setAttribute",
    "selector": "img#avatar",
    "attribute": "src",
    "value": "http://www.iconwanted.com/downloads/david-lanham/heroes-and-villains/png/128x128/batman.png",
  },
  {
    "description": "Use Bing for search instead of Google",
    "action": "setAttribute",
    "selector": "a[href='http://google.com']",
    "attribute": "href",
    "value": "http://bing.com",
  },
  {
    "description": "Open search in new tab",
    "action": "setAttribute",
    "selector": "a.search-target",
    "attribute": "target",
    "value": "_blank",
  },
  {
    "description": "Hide h3 in footer",
    "action": "hide",
    "selector": "footer h3",
  },
  {
    "description": "Show a text that was hidden",
    "action": "show",
    "selector": "footer p",
  },
  {
    "description": "Set header style to underline",
    "action": "setStyleAttribute",
    "selector": "h1, h5",
    "attribute": "text-decoration",
    "value": "underline",
  },
];
